FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY extractor/ ./extractor/

CMD ["python", "-m", "extractor.main", "--ufs", "SP", "MG", "GO"]
